version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=StPractice.settings
      - DEBUG=1
    depends_on:
      - db

  db:
    image: mysql:8.0
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=yourrootpass
      - MYSQL_DATABASE=yourdb
      - MYSQL_USER=youruser
      - MYSQL_PASSWORD=yourpass
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data: