# Generated by Django 5.1.3 on 2025-03-21 07:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=100, verbose_name='Ответ')),
                ('count', models.IntegerField(verbose_name='Полученный балл')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Ваш текст')),
                ('is_link', models.BooleanField(default=False, verbose_name='Состоит в чате?')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Заявка одобрена?')),
                ('comment', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Отзыв')),
                ('date_sub', models.DateTimeField(auto_now=True, verbose_name='Дата подачи')),
                ('date_end', models.DateTimeField(blank=True, null=True, verbose_name='Дата изменения')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('ВК', 'ВК'), ('ТГ', 'ТГ'), ('Почта', 'Почта'), ('Телефон', 'Телефон')], max_length=100, verbose_name='Тип контакта')),
                ('data', models.CharField(max_length=100, verbose_name='Реквезит')),
            ],
        ),
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название направления')),
                ('description', models.TextField(blank=True, max_length=10000, null=True, verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название мероприятия')),
                ('description', models.TextField(blank=True, max_length=10000, null=True, verbose_name='Описание')),
                ('stage', models.CharField(choices=[('Редактирование', 'Редактирование'), ('Набор участников', 'Набор участников'), ('Формирование команд', 'Формирование команд'), ('Проведение мероприятия', 'Проведение мероприятия'), ('Мероприятие завершено', 'Мероприятие завершено')], default='Редактирование', max_length=50, verbose_name='Этап')),
                ('start', models.DateField(verbose_name='Дата начала')),
                ('end', models.DateField(verbose_name='Дата окончания')),
                ('end_app', models.DateField(verbose_name='Дата окончания приема заявок')),
            ],
        ),
        migrations.CreateModel(
            name='FunctionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('type_function', models.CharField(choices=[('Робот', 'Робот'), ('Триггер', 'Триггер')], max_length=10000, verbose_name='Тип действия')),
                ('name', models.CharField(max_length=10000, verbose_name='Название функции')),
                ('config', models.CharField(max_length=10000, verbose_name='Конфигурация')),
            ],
        ),
        migrations.CreateModel(
            name='OrgChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('ВК', 'ВК'), ('ТГ', 'ТГ')], max_length=100, verbose_name='Тип чата')),
                ('name', models.CharField(max_length=100, verbose_name='Название чата')),
                ('description', models.CharField(max_length=100, verbose_name='Описание чата')),
                ('link', models.CharField(max_length=100, verbose_name='Ссылка на чат')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('telegram', models.CharField(blank=True, max_length=100, null=True, verbose_name='Telegram')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='Email')),
                ('surname', models.CharField(blank=True, max_length=100, null=True, verbose_name='Фамилия')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя')),
                ('patronymic', models.CharField(blank=True, max_length=100, null=True, verbose_name='Отчество')),
                ('course', models.IntegerField(blank=True, null=True, verbose_name='Курс')),
                ('university', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название университета')),
                ('vk', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ссылка VK')),
                ('job', models.CharField(blank=True, max_length=100, null=True, verbose_name='Место работы')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, verbose_name='Вопрос')),
                ('count', models.IntegerField(verbose_name='Количество баллов за вопрос')),
            ],
        ),
        migrations.CreateModel(
            name='Robot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название робота')),
                ('description', models.TextField(blank=True, max_length=10000, null=True, verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Организатор', 'Организатор'), ('Руководитель', 'Руководитель'), ('Куратор', 'Куратор')], default='На согласовании', max_length=50, verbose_name='Название роли')),
            ],
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(blank=True, max_length=10000, null=True, verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(blank=True, max_length=10000, null=True, verbose_name='Описание')),
                ('is_positive', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Status_order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=1, verbose_name='Позиция')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название теста')),
                ('description', models.TextField(blank=True, max_length=10000, null=True, verbose_name='Описание')),
                ('entry', models.IntegerField(verbose_name='Порог прохождения в %')),
            ],
        ),
        migrations.CreateModel(
            name='Trigger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название триггера')),
                ('description', models.TextField(blank=True, max_length=10000, null=True, verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='True_Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('true_answer', models.CharField(max_length=100, verbose_name='Правильный ответ')),
            ],
        ),
    ]
