# Generated by Django 5.1.3 on 2025-03-21 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
        ('plan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plan.project'),
        ),
        migrations.AddField(
            model_name='application',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plan.team'),
        ),
        migrations.AddField(
            model_name='application',
            name='direction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.direction'),
        ),
        migrations.AddField(
            model_name='direction',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directions', to='crm.event'),
        ),
        migrations.AddField(
            model_name='application',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='crm.event'),
        ),
        migrations.AddField(
            model_name='orgchat',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.event'),
        ),
        migrations.AddField(
            model_name='contact',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.profile'),
        ),
        migrations.AddField(
            model_name='application',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.profile'),
        ),
        migrations.AddField(
            model_name='answer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.profile'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.question'),
        ),
        migrations.AddField(
            model_name='functionorder',
            name='robot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.robot'),
        ),
        migrations.AddField(
            model_name='role',
            name='users',
            field=models.ManyToManyField(related_name='users', to='crm.profile'),
        ),
        migrations.AddField(
            model_name='event',
            name='specializations',
            field=models.ManyToManyField(related_name='specializations', to='crm.specialization', verbose_name='Специализации'),
        ),
        migrations.AddField(
            model_name='application',
            name='specialization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.specialization'),
        ),
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.status'),
        ),
        migrations.AddField(
            model_name='status_order',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.event'),
        ),
        migrations.AddField(
            model_name='status_order',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.status'),
        ),
        migrations.AddField(
            model_name='test',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.event'),
        ),
        migrations.AddField(
            model_name='question',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.test'),
        ),
        migrations.AddField(
            model_name='functionorder',
            name='trigger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.trigger'),
        ),
        migrations.AddField(
            model_name='true_answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.question'),
        ),
    ]
