# Generated by Django 5.1.3 on 2025-03-30 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='functionorder',
            name='name',
        ),
        migrations.AddField(
            model_name='functionorder',
            name='status_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='functions', to='crm.status_order'),
        ),
        migrations.AddField(
            model_name='robot',
            name='parameters_template',
            field=models.TextField(default='{}', help_text='JSON-схема параметров', verbose_name='Шаблон параметров'),
        ),
        migrations.AddField(
            model_name='robot',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Статус активности'),
        ),
        migrations.AddField(
            model_name='robot',
            name='type_action',
            field=models.CharField(default='', max_length=100, verbose_name='Тип действия'),
        ),
        migrations.AddField(
            model_name='trigger',
            name='parameters_template',
            field=models.TextField(default='{}', help_text='JSON-схема параметров', verbose_name='Шаблон параметров'),
        ),
        migrations.AddField(
            model_name='trigger',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Статус активности'),
        ),
        migrations.AddField(
            model_name='trigger',
            name='type_condition',
            field=models.CharField(default='', max_length=100, verbose_name='Тип условия'),
        ),
        migrations.AlterField(
            model_name='functionorder',
            name='config',
            field=models.JSONField(verbose_name='Конфигурация параметров'),
        ),
        migrations.AlterField(
            model_name='functionorder',
            name='position',
            field=models.PositiveIntegerField(verbose_name='Позиция в очереди'),
        ),
        migrations.AlterField(
            model_name='functionorder',
            name='type_function',
            field=models.CharField(choices=[('robot', 'Робот'), ('trigger', 'Триггер')], max_length=10, verbose_name='Тип действия'),
        ),
        migrations.AddConstraint(
            model_name='functionorder',
            constraint=models.UniqueConstraint(fields=('status_order', 'position'), name='unique_status_order_position'),
        ),
    ]
