# Generated by Django 5.1.3 on 2025-03-21 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Описание пункта')),
                ('description', models.CharField(max_length=500, verbose_name='Описание пункта')),
            ],
        ),
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500, verbose_name='Описание пункта')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Выполнено')),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan.checklist')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название проекта')),
                ('description', models.TextField(blank=True, max_length=10000, null=True, verbose_name='Описание')),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.direction')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название ссылки')),
                ('link', models.CharField(max_length=10000, verbose_name='Ссылка')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan.project')),
            ],
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название этапа')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='plan.project')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название')),
                ('description', models.TextField(max_length=10000, verbose_name='Описание')),
                ('start', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('end', models.DateTimeField(blank=True, null=True, verbose_name='Время закрытия задачи')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks_creators', to='crm.profile', verbose_name='Создатель задачи')),
                ('parent_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='plan.task', verbose_name='Родительская задача')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan.project', verbose_name='Проект')),
                ('responsible_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.profile', verbose_name='Ответственный')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan.stage', verbose_name='Статус')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=10000, verbose_name='Текст')),
                ('file', models.FileField(blank=True, null=True, upload_to='comments', verbose_name='Файл')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.profile')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='plan.task')),
            ],
        ),
        migrations.AddField(
            model_name='checklist',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist', to='plan.task'),
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('is_agreed', models.BooleanField(default=False)),
                ('curator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curator', to='crm.profile')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plan.project')),
                ('students', models.ManyToManyField(blank=True, related_name='teams', to='crm.profile')),
            ],
        ),
    ]
